name: Create a New Program
description: Use this template to add a new program to the repository.

title: "[gh-automator] New Program: "
labels: ["gh-automator-new-program"]

body:
  - type: markdown
    attributes:
      value: |
        ⚠️ PLEASE DO NOT USE THIS TEMPLATE yourself. Use the `dockyard` Web UI, which will redirect you to this template with all information pre-filled.

  - type: input
    id: id
    attributes:
      label: What is the slug of the program?
      placeholder: "summer-of-baking"
    validations:
      required: true

  - type: input
    id: name
    attributes:
      label: What is the name of the program?
      placeholder: "Summer of Baking"
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: What is the type of the program?
      multiple: false
      options:
        - ysws
        - flagship
    validations:
      required: true

  - type: dropdown
    id: draft
    attributes:
      label: Should this program be a draft?
      description: Draft programs will not appear on the live site.
      multiple: false
      options:
        - "true"
        - "false"
    validations:
      required: true

  - type: input
    id: description
    attributes:
      label: Provide a short description or tagline.
      placeholder: "A program to explore creative baking techniques."
    validations:
      required: true

  - type: input
    id: ys
    attributes:
      label: What is the YS (Your Ship)?
      placeholder: "Bake a new item every weekend"
    validations:
      required: true

  - type: input
    id: ws
    attributes:
      label: What is the WS (We Ship)?
      placeholder: "A cookbook, a badge, and promotion on our site"
    validations:
      required: true

  - type: input
    id: website
    attributes:
      label: Program website (if exists)
      placeholder: "https://summer-of-baking.hackclub.com"
    validations:
      required: false

  - type: input
    id: slack-link
    attributes:
      label: Slack link
      placeholder: "https://hackclub.slack.com/archives/C094J1QDU72"
    validations:
      required: true

  - type: input
    id: slack-name
    attributes:
      label: Slack channel name (without \#)
      placeholder: "summer-of-baking"
    validations:
      required: true

  - type: input
    id: timelines
    attributes:
      label: Timelines
      placeholder: "YUH let dockyard fill this in"
    validations:
      required: true

  - type: input
    id: ships
    attributes:
      label: Ships
      placeholder: "YUH let dockyard fill this in"
    validations:
      required: true
