name: GH Automator
on:
  issues:
    types: [labeled]

jobs:
  issue-automator:
    if: github.event.label.name == 'gh-automator-approved'
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          ref: main
      - uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2
        with:
          bun-version-file: "package.json"

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run the Action
        run: |
          bun run gh-automator
          bun run build:api
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ISSUE: "${{ github.repository}}#${{ github.event.issue.number }}"

      - name: Run the Action
        uses: devops-infra/action-commit-push@master
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          commit_message: "chore: api-data-update"
          target_branch: api-data-update-${{ github.run_id }}

      - name: Check if branch exists
        id: check_branch
        run: |
          if git ls-remote --exit-code --heads origin api-data-update-${{ github.run_id }}; then
            echo "branch_exists=true" >> $GITHUB_OUTPUT
          else
            echo "branch_exists=false" >> $GITHUB_OUTPUT
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create PR and Merge
        if: ${{ steps.check_branch.outputs.branch_exists == 'true' }}
        run: |
          gh pr create --base main --head api-data-update-${{ github.run_id }} --title "API Data Update" --body "fixes #${{ github.event.issue.number }}  Automated API update. This PR is auto-generated by the issue automator workflow."
          gh pr merge --squash --delete-branch --admin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4
        with:
          path: "api/"

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4
